# Generated by Django 5.0.7 on 2024-12-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('track_id', models.CharField(max_length=22, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artists', models.JSONField()),
                ('year', models.IntegerField()),
                ('explicit', models.BooleanField()),
                ('first_artist', models.CharField(max_length=255)),
                ('genres', models.JSONField()),
                ('genres_limited', models.JSONField()),
                ('valence', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('key', models.IntegerField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
            ],
        ),
    ]
